encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>', views.access_entry, name="access_entry"),
    path('create/', views.create_page, name='create'),
    path('random/', views.random_page, name="random"),
    path('search/', views.search_page, name='search'),
    path('edit/<str:title>', views.edit_page, name='edit')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = "wiki"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

encyclopedia/templates/encyclopedia/create_page.html
{% extends "layouts/main_layout.html" %}

{% block title %}Create Page{% endblock title %}

{% block nav %}
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
{% endblock nav %}

{% block body %}
                <h1>Create a new page</h1>
                {% if error %}
                    <h3>{{ error }}</h3>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form}}
                <input type="submit" value="Submit">
                </form>
{% endblock body %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "layouts/main_layout.html" %}

{% block title %}Create Page{% endblock title %}

{% block nav %}
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
{% endblock nav %}

{% block body %}
                <h1>Edit the Page's Content:</h1>
                <h2> {{ title }} </h2>
                {% if error %}
                    <h3>{{ error }}</h3>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form}}
                <input type="submit" value="Save">
                </form>
{% endblock body %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "layouts/main_layout.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block nav %}
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create Page</a>
                </div>
{% endblock nav %}

{% block body %}
    {% if entry %}
        {{entry | safe}}
    {% else %}
    {% comment %} Replace with a bootstrap element {% endcomment %}
        <h1> This Page Doesn't Exist Yet</h1>
    {% endif %}
    <a href="{% url "encyclopedia:edit" title %}">Edit page</a>
{% endblock body %}

encyclopedia/templates/encyclopedia/index.html
{% extends "layouts/main_layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block nav %}
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create Page</a>
                </div>
                
{% endblock nav %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li> 
                <a href="{% url 'encyclopedia:access_entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/layouts/main_layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action=" {% url "encyclopedia:search" %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                {% block nav %}         
                {% endblock %}
                <div>
                    <a href="{% url "encyclopedia:random" %}">Random Page</a>
                </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>